### ISSUE TITLE
Date/DateTime regression (expected Int:D but got Int (Int))

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2615]
```
t/02-Workdate_basic.t ......... 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 6/18 subtests 
# Testing the creation of a Workdate from a Date
# Testing Date and Workdate operators
Type check failed for return value; expected Int:D but got Int (Int)
  in block <unit> at t/03-Workdate_Date.t line 27
```

Bisected: 9f28a4235734af626b555a4c64a63388f6ca70a2

See https://github.com/perl6-community-modules/Date-WorkdayCalendar

:pancakes:

**Comment by lizmat** [comment]
spectesting a fix

**Comment by lizmat** [comment]
Fixed with 9295616422

**Comment by lizmat** [comment]
Added tests with https://github.com/perl6/roast/commit/529b04d2f5

**Comment by AlexDaniel** [comment]
@lizmat There's a [similar issue](https://gist.github.com/AlexDaniel/13b77433ecfcf6478106bfab6fd6b8b4#file-output_datetime-extended_0-1-0) with [DateTime::Extended](https://github.com/FCO/DateTime-Extended).

**Comment by AlexDaniel** [comment]
@lizmat also, [TauStation](https://github.com/zoffixznet/perl6-Games-TauStation-DateTime) still fails (mentioned in the second comment). So currently two modules need to be looked at.

**Comment by lizmat** [comment]
Fixed with 3488a65ed7, tests added with https://github.com/perl6/roast/commit/9d55fd0c0e
