### ISSUE TITLE
The .= operator doesn't work for subscripts

### ISSUE THREAD

**Issue by 2colours** [rakudo/rakudo#4996]
## The Problem
When trying to use .= with [$value] or {$value} on the right hand-side, rather than doing $x = $x[$value], the call fails, stating that there is no method that could fulfill the code. This might very well be true from a technical point of view but it's still unexpected and a bad experience from the user's point of view.

## Expected Behavior
```
my $nested = { dummy => <actual values> };
$nested .= <dummy>;
say $nested; # (actual values)
```
## Actual Behavior
The second line throws: `No such method '&postcircumfix:<{ }>' for invocant of type 'Hash'`
## Environment
* Operating system: Ubuntu 20.04
* Compiler version (`perl6 -v` or `raku -v`): Welcome to Rakudo™ v2022.04. Implementing the Raku® Programming Language v6.d. Built on MoarVM version 2022.04.

**Comment by 2colours** [comment]
Also, maybe I'm misremembering but I think there was a general issue for the precedence of `.=` which is higher than `.`, also very much like a gotcha.

**Comment by lizmat** [comment]
Full stack trace:
````
No such method '&postcircumfix:<{ }>' for invocant of type 'Hash'
   at SETTING::src/core.c/Exception.pm6:64  (/Users/liz/Github/rakudo/install/share/perl6/runtime/CORE.c.setting.moarvm:throw)
 from gen/moar/Metamodel.nqp:60  (/Users/liz/Github/rakudo/install/share/perl6/lib/Perl6/Metamodel.moarvm:throw_or_die)
 from gen/moar/BOOTSTRAP/v6c.nqp:5159  (/Users/liz/Github/rakudo/install/share/perl6/lib/Perl6/BOOTSTRAP/v6c.moarvm:report-method-not-found)
 from gen/moar/BOOTSTRAP/v6c.nqp:5134  (/Users/liz/Github/rakudo/install/share/perl6/lib/Perl6/BOOTSTRAP/v6c.moarvm:)
 from -e:2  (<ephemeral file>:<unit>)
 from -e:1  (<ephemeral file>:<unit-outer>)
````

**Comment by lizmat** [comment]
The right hand side of a `.=` expects something that is valid on the right side of a `.`.

And since `my %h = a => 42; dd %h.<a>` is valid, `my $h = { a => 42 }; dd $h .= <a>` should also work.

Feels to me the codegenning of `.=` needs a little work in this respect.  @niner @jnthn something to fix now, or let remember this for RakuAST fixes?

**Comment by lizmat** [comment]
To be clear, `$h .= <foo>` should be codegenned as `$h = $h<foo>`.

**Comment by patrickbkr** [comment]
> Also, maybe I'm misremembering but I think there was a general issue for the precedence of `.=` which is higher than `.`, also very much like a gotcha.

https://github.com/rakudo/rakudo/issues/4863

**Comment by salortiz** [comment]
> … the precedence of `.=` which is higher than `.`

No, the precedence of both is *almost* the same, so associativity wins:

```raku
class B { method m { note 'In m'; self } };
class A { method b is rw { note 'In b'; $ = B.new } };

my A $a;
$a .= new; # Mutate $a;
say $a . b .= m;
# In b
# In m
# B.new

```

**Comment by 2colours** [comment]
> > Also, maybe I'm misremembering but I think there was a general issue for the precedence of `.=` which is higher than `.`, also very much like a gotcha.
> 
> #4863

A gotcha at best, downright a bug at worst. It all depends on the perspective.

I think it was a "marketing mistake" to repeatedly sell `.=` as an operator analoguous to `+=`, `*=` and the likes when it's a methodoperator and as such, much more like `.?`, `.&` and all.

Which reminds me @salortiz `$a .= &sub`˙is actually valid, as opposed to your statement: `(...) if and only if bar is a valid method name of foo`.  
I don't think these differences are planned, perhaps even less so than the high precedence of `.=`. In which case, I would advise against treating the current behavior authoritative and sell it as a feature. When this came up, it @lizmat encouraged me to have an issue for it as something that might be better targeted with the RakuAST way of compilation.

**Comment by salortiz** [comment]
@2colours,

Yes, `$a .= &sub` is valid. In the table above I deliberately don't include `.&…`, `.$…`, `."…`, etc., because these constructs aren't `dotty` tokens, only alternative forms of method call, so valid with both `.` and `.=`.

I don't known where you "buyed" the idea of `.=` as analogous to composed assignment operators, but in #4863 I left a note about that mistake.

**Comment by 2colours** [comment]
@salortiz 

The point is that it's an arbitrary difference in the implementation that carries on in the terminology that you present.

https://docs.raku.org/language/operators#index-entry-methodop_.&
https://docs.raku.org/language/operators#methodop_.?
https://docs.raku.org/language/operators#methodop_.postfix_/_.postcircumfix

All we get to know about any of them is that they "aren't real operators but syntax special-cased in the compiler".

I think two things follow from this:
1. we shouldn't invent a new level of differentiation based on implementation details. If they look alike according to the documentation, and they don't behave alike, that should be considered a gotcha at best.
2. not unrelated to what I said so far, "syntax special-casing" is a characteristic of the underlying compiler, and as such, _can be subject to change_ at any time. It's a bit hard to talk about something I don't quite grasp but I think these "syntax special-casings" will become less "special" and much more the normal way of doing things when RakuAST lands. Now, if in RakuAST, all the current special-casings go out of the window, I suppose all the carried luggage (implied behavior and terminology) can go with it _at no cost_.

> I don't known where you "buyed" the idea of .= as analogous to composed assignment operators,

Perhaps at the same place where @patrickbkr who has been here for much longer, "bought" it. I don't have a collection down in my pocket but _trust me_, it was a recurring theme of presentations and possibly articles about Raku that "we have op= not only for normie stuff like + and - but the method call itself!".  

Mind you, it could have been sold as "mutating method call", and there are places were it's presented like that, but that interpretation is not overwhelming (not unrelated to the fact that method calls can be mutating by themselves).  
I had a discussion about that [on the IRC not so long ago](https://irclogs.raku.org/raku/2022-09-20.html), even explicitly asking the question [about the two possible interpretations](https://irclogs.raku.org/raku/2022-09-20.html#11:10), to which, again, @lizmat said that it's "clearly an assignment". Actually, out of the 3 people involved in that discussion, Voldenet expressed preference for the behavior @patrickbkr expected in #4863 and @alabamenhu said:

> `.=`  is a method operator.  **It's the method op `.` with the metaop `=`**    The  catch is just that (right now) that IIRC it needs to be special cased in  the compiler

Of course, any of these people, including you and me, can be just simply wrong about something but it's undeniable that seeing `.=` as a shorthand assignment with the infix `.` is an existing and prevalent interpretation even within knowledgeable users, and not a "mistake".

As a sidenote, I'm not against the concept of a "mutating method call" in a [similar way to Ruby](https://launchschool.medium.com/ruby-objects-mutating-and-non-mutating-methods-78023d849a5f) - but, if that was the intention, perhaps it would have been a better idea to pick a token that doesn't read like an assignment.

**Comment by niner** [comment]
Don't have time to really follow this discussion or read these docs, but I just wanted to point out that https://design.raku.org/S03.html#Assignment_operators may contain some background information on this.

**Comment by 2colours** [comment]
As a TL;DR, I think there are two divergent topics here:
1. one is about the broader interpretation of the `.=` operator - that probably rather belongs to https://github.com/rakudo/rakudo/issues/4863, and since it's not a "Rakudo bug", it might even deserve a general Problem-solving issue
2. the one related to this exact issue, where my main point would simply be: please refrain from treating the current implementation authoritative, especially with regards to discussing whether something is a bug or not. Pointing out why something works in a certain way doesn't make it automatically right, especially if it's deep in the compiler design territory. And these issues can get a whole different context in RakuAST that strongly affects the way syntax turns into opcodes.

**Comment by jubilatious1** [comment]
**> The .= operator doesn't work for subscripts**

I've always thought this was by design, not by accident. Same reason negation of `unless` is disallowed:  because it is confusing. Anyway below balks because the code is legitimately confusing:
```
[3] > my @a = 'a'...'z'
[a b c d e f g h i j k l m n o p q r s t u v w x y z]
[4] > @a.[0] .=[1]
No such method '&postcircumfix:<[ ]>' for invocant of type 'Str'
  in block <unit> at <unknown file> line 1

[4] > @a.[0] .= [1]
No such method '&postcircumfix:<[ ]>' for invocant of type 'Str'
  in block <unit> at <unknown file> line 1

[4] > @a.[0] .= .[1]
===SORRY!=== Error while compiling:
Missing required term after infix
------> @a.[0] .=⏏ .[1]
    expecting any of:
        dotty method or postfix
[4] > @a.[0] = @a.[1]
b
[5] > say @a
[b b c d e f g h i j k l m n o p q r s t u v w x y z]
[5] >
```
And (below correctly balks):

```
[5] > my @b = 'a'...'z'
[a b c d e f g h i j k l m n o p q r s t u v w x y z]
[6] > @b[0] .= @b[1]
===SORRY!=== Error while compiling:
Missing infix inside []
------> @b[0] .= @b[⏏1]
    expecting any of:
        bracketed infix
        infix
        infix stopper
[6] > @b.[0] .= @b.[1]
===SORRY!=== Error while compiling:
Malformed postfix call
------> @b.[0] .= @b.⏏[1]
[6] > @b.[0] = @b.[1]
b
[7] > say @b
[b b c d e f g h i j k l m n o p q r s t u v w x y z]
[7] >
```

Don't even get me started on hyper calls... .

@salortiz

**Comment by 2colours** [comment]
To be frank, I'm _very_ skeptical of any argument suggesting that something is disallowed in Raku "because it is confusing". That's very subjective and I think Raku actually does a great job at allowing you to write confusing things that you can't read 2 days later.

The irony is that while I don't think these examples are confusing, you seem to get it wrong. `@a[0] .= [1]` stands for `@a[0] = @a[0][1]` for sure, and not `@a[0] = @a[1]`. That's as if you mistook `$pair.value .= succ` for `$pair.value = $pair.succ`.

**Comment by jubilatious1** [comment]
Hi @2colours , how could I possibly get it wrong? After all, I'm the new user you're trying to recruit. If there's a mis-understanding, it isn't from lack of trying to read the Docs, nor lack of writing one-liners, nor lack of exploring the REPL. 

Maybe I (slightly) mis-remembered what the Raku Docs said, but here's a direct quote:

_"You cannot use else or elsif with unless because that ends up getting confusing. "_
https://docs.raku.org/syntax/unless

So you have _within the Raku Docs__, evidence that __not-confusing-the-user__ is a design principle.

As for Array indexing, please show your best code for `@a[0] .= [1]`. If indeed it is a shortcut for `@a[0] = @a[0][1]`, then the two code examples below should return the same answer--but they do not:
```raku
> my @c;
[]
> @c[0] .= [1]
No such method '&postcircumfix:<[ ]>' for invocant of type 'Any'
  in block <unit> at <unknown file> line 1

> @c[0] = @c[0][1]
(Any)
>
```

**Comment by 2colours** [comment]
> So you have _within the Raku Docs_, evidence that **not-confusing-the-user** is a design principle.

I don't think this generalization is appropriate, the way you are using it.

The unless-else case is easily justifiable in many ways and it can be summarized as "(while we do like giving the user choices for the sake of the choice,) we won't insist on completely redundant structures that create extra inversions in logic and nonsensical English phrasings". It doesn't have a lot in common with subjective perception of what is confusing and what isn't. Actually, if we were to collect features of Raku that somebody might deem confusing, I probably wouldn't add `.=` to that list, if not for the surprisingly high precedence it has. It does allow for DRY-er code, that's for sure, and I didn't make the demand up, just genuinely stumbled on it while working on something.



> As for Array indexing, please show your best code for `@a[0] .= [1]`. If indeed it is a shortcut for `@a[0] = @a[0][1]`, then the two code examples below should return the same answer--but they do not:

Touché. This is what this very issue is about. "The .= operator doesn't work for subscripts."

By the way, almost a year later, now I do have a clue what the error is trying to tell us. It shows that the grammar is actually ready to support this behavior, and the only problem is that it is trying to look up the operator as a method, rather than a subroutine. It might be solvable within the core.

**Comment by jubilatious1** [comment]
I don't think we're on the same page.

> Touché. This is what this very issue is about. "The .= operator doesn't work for subscripts."

Even if it did work for subscripts... 
...how do you propose to assign a value to the container being added by  `@a[0] = @a[0][1]` ??

**Comment by 2colours** [comment]
I don't understand the question. `@a[0] = @a[0][1]` makes perfect sense if you have nested arrays, and `@a[0] .= [1]` should generate the same (or at least compatible) bytecode. _It very nearly does_ already.

Just to give you an illustration, I extracted the QAST output of `@a[0] .= &postcircumfix:<[ ]>(1)` (which does work as I want it to) and `@a[0] .= [1]`. You can see how close they are.

![image](https://github.com/rakudo/rakudo/assets/37218286/4d68b07f-9b97-46cb-9439-e329aae9b823)

**Comment by jubilatious1** [comment]
> `@a[0] = @a[0][1]` makes perfect sense if you have nested arrays...

What would make perfect sense is publicizing a syntax that assigns a value to the second dimension added by `[1]` ___within the same statement___, and working from there. It would seem to be _"premature-optimization"_ otherwise.

**Comment by 2colours** [comment]
I don't understand this either. There is only one statement in either case, except you don't repeat yourself with the `$nested .= <key>` syntax, and it is indeed supposed to work. This is what I opened the issue for, and this point stands.

**Comment by jubilatious1** [comment]
how do you give `<key>` a value?

**Comment by 2colours** [comment]
I'm running short of ideas what you actually want... I opened an issue for a very definite thing, providing a snippet of what I expected to work and what the actual behavior is. If you are concerned about the semantics, that snippet should have been enough to explain it, but here it goes for the last time: `expression .= lookup` stands for `expression = expression.lookup` and since `expression.[index]`, `expression.<key>` etc. happen to fit this formula, the expectation is for them to work when you want to narrow down an unnecessarily nested data structure. If you are concerned about the implementation - not sure you should be, or how that would be constructive for the issue in the first place - don't worry, it's not weird, it's doable, and it will probably only become more doable with the RakuAST frontend.

**Comment by jubilatious1** [comment]
Yes, I think this conversation has run it's course, although I'll try again. 

In quite a few languages when you use the `=` operator, you're doing ___assignment___. 
And when you're using `[]` post-circumfix square brackets, you're doing some sort of subsetting operation. 

In the __R-programming Language__ ([r-project.org](https://www.r-project.org)), here's what multiple postcircumfix square brackets does:
```R
> LETTERS
 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S" "T" "U" "V" "W" "X" "Y" "Z"
> LETTERS[1:10][6:10]
[1] "F" "G" "H" "I" "J"
> 
```

This seems to me simple and intuitive. The built in `LETTERS` vector consists of 26 elements, and when you subset via `LETTERS[1:10]` you get back the first 10 letters of the alphabet. That `[1:10]` sub-setting post-circumfix square bracket code works on the array and modifies the return (the original `LETTERS` built-in vector remains unchanged).

What happens when you repeat that sub-setting post-circumfix square bracket code, as in `LETTERS[1:10][6:10]` ?  You get back elements at index `6:10` of the first-subsetted vector.

So following those simple rules, you get the following:
```R
> LETTERS[21:26]
[1] "U" "V" "W" "X" "Y" "Z"
> LETTERS[21:26][1:3]
[1] "U" "V" "W"
> 
```

The first `[21:26]` subsetting-code gives you letters "U"-through-"Z", and now this return contains 6 elements indexed 1-through-6. When you append the second`[1:3]` subsetting code the final return is thus letters "U"-through-"W".

I don't know what to make of your nested-array syntax. Isn't there syntax for using `;` semicolons within  the `[]` square brackets for creating shaped-arrays? 

Regardless, it's not clear to me what you're gaining from a `.=` construct working on subsetting elements alone. Here's what you get if you do it right in the R-programming language:

```R
> a_vector <- LETTERS
> a_vector <- LETTERS[21:26]
> a_vector
[1] "U" "V" "W" "X" "Y" "Z"
> a_vector <- a_vector[1:3]
> a_vector
[1] "U" "V" "W"
> 
```

Composite operators like `~=` and `+=` are for building up data structures, and/or accumulating. Not for subsetting.


@pmichaud

**Comment by jubilatious1** [comment]
@niner wrote:

> Don't have time to really follow this discussion or read these docs, but I just wanted to point out that https://design.raku.org/S03.html#Assignment_operators may contain some background information on this.

```raku
 > my @foo = 'a'
[a]
 > @foo ,= 1,2,3
(\Array_2672985475536 = [Array_2672985475536 (1 2 3)])
 > say @foo
(\Array_2672985475536 = [Array_2672985475536 (1 2 3)])
 >
```

**Comment by vrurg** [comment]
@jubilatious1 Have you tried your R examples in Raku?

Think of it logically. A post-whatever operator is applied to an expression on its left side. I.e. in case of `@a[0][1]` `[1]` applies to `@a[0]`: `(@a[0])[1]`. Apparently, we're trying to subscript a scalar. 

But Raku implements slicing of arrays. Therefore `(@a[3..10])[2..4]` -> `@a[3..10][2..4]`. Try that.

I don't see how is it less intuitive than in R. Same logic of "take an expression, apply an op to it".

Next, the `,=` example. This code is a source of confusion for not you alone. But then again, assignment metaop is documented to be "take LHS, take RHS, combine them using the op we're applied to, assign back into LHS". From this point of view I don't agree it deviates from anything. Well, yes, before the Great List Refactor it was doing what you expect from it. But special casing is what was killing Perl in the eyes of many. So, I don't agree we need it here. Instead, let's see what happens, step by step.

`my @a = <a b>; @a ,= 1,3`. Our LHS is `['a', 'b']`. Our RHS is `(1, 3)`. Therefore what we get is `@a = @a, (1, 3)`. Printing @a would result in something like `(\Array_4262025111728 = [Array_4262025111728 (1 3)])` because the array references itself. BTW, at some point it was causing infinite recursion.

What we normally do when we need to "attach" a new iterable to an existing positional? We slip it: `@a ,= |(1, 3)`. It gives us slightly different output: `(\Array_5989957532680 = [Array_5989957532680 1 3])`. But still not what is expected. This is because LHS follows the single argument rule yet.

But it's Raku, isn't it?

`|@a ,= |(1, 3); say @a`.

Voila? Unfortunately, no because in this case the assignable LHS is a `Slip`. This is where I see some room for improvement, but not sure how big could that be. The above case is pretty apparent and one may expect the assignment to take place into `@a`. But where do we stop in something like `|$obj.array-attribute ,= 1,3`? Are we assigning into `$obj` or into the `array-attribute`? What if the method returns a `Proxy`? Too many special cases with a wide space for disagreements on how to do it.

**Comment by 2colours** [comment]
> From this point of view I don't agree it deviates from anything. Well, yes, before the Great List Refactor it was doing what you expect from it.

Roast formally contains that test, only allowing Rakudo to skip it, with the informal comment that it should be fixed by hand after the Great List Refactor. The formal containment makes it factual that Rakudo deliberately differs from the language specification. If that wasn't the intention, the test should be removed, or even better, replaced with the test for the supposed actual behavior.

So much for the facts, back to the opinion: the so-called "list assignment" itself is a form of special casing that has caused a considerable amount of headaches by now, both from syntax perspective and the behavior. In some sense, "it turned me into what I am today" because [it prompted me to open my first ever Raku issue](https://github.com/Raku/problem-solving/issues/307). That one could probably be solved because there is a clear 1-to-1 correspondence between the assigned pieces.

On the other hand, you are most probably right that the way even something as mundane as `($list, 2, 3)` works, `,=` is mostly a red herring. It irks me and I still need to think about it because the temptation is real but it would definitely require a very intrusive change to work out of the box... Scalars can implicitly unbox, basically it would require the same behavior for compound data structures that contain scalars, and then the generic case with Proxies would still be a big question...

**Comment by vrurg** [comment]
> the test should be removed, or even better, replaced with the test for the supposed actual behavior.

I'd say this is the way to go.

**Comment by jubilatious1** [comment]
@lizmat wrote:
> To be clear, `$h .= <foo>` should be codegenned as `$h = $h<foo>`.

```raku
[6] > my %h = %('a' => 0, 'b' => 1, 'c' => 2)
{a => 0, b => 1, c => 2}
[7] > say %h<a>
0
[7] > %h =  %h<a>
Odd number of elements found where hash initializer expected:
Only saw 1 element
  in block <unit> at <unknown file> line 1

[7] > $h =  %h<a>
===SORRY!=== Error while compiling:
Variable '$h' is not declared.  Did you mean '%h'?
------> <BOL>⏏$h =  %h<a>
[7] > my $h =  %h<a>
0
[8] > $h.say
0
[8] > %h .= <a>
No such method '&postcircumfix:<{ }>' for invocant of type 'Hash'
  in block <unit> at <unknown file> line 1

```
Above ___feels___ wrong. If you have a `hash` and want to whittle it down to one `pair`, a `.=` mutating-assignment operator won't work for you. And then you assign to a `$`-sigiled variable and it works--but you're changing sigils.

So you have to start with an `$`-sigiled `hash`, which also feels wrong. And still doesn't get you the `pair`:

```raku
[8] > my $h = %('a' => 0, 'b' => 1, 'c' => 2)
{a => 0, b => 1, c => 2}
[9] > $h .= <a>
No such method '&postcircumfix:<{ }>' for invocant of type 'Hash'
  in block <unit> at <unknown file> line 1

[9] > $h = $h.<a>
0
[10] >
 > my $h = %('a' => 0, 'b' => 1, 'c' => 2)
{a => 0, b => 1, c => 2}
[12] > $h .= $h.<a>
===SORRY!=== Error while compiling:
Malformed postfix call
------> $h .= $h.⏏<a>
```

**Comment by vrurg** [comment]
@jubilatious1 are you sure you understand what exactly you want to achieve? One way or another, `.<a>` or `.{"a"}` are giving you a value. To get a `Pair` you clearly need `:p` adverb: `%h<a>:p`.

I see no point in your references to `$` sigil. I mean, do you really understand what's the difference between `%h` and `$h = %()`?

So far, it is apparent that `$h .= <a>` syntax is broken. `%h .= <a>` will never work because you get a single value and try to assign it back into a hash; assuming that the `a` key contains a simple value, not an iterable or a pair. But as soon as `.=` gets fixed `%h .= <a>:p` would result in trimming down the hash to a single key.

**Comment by jubilatious1** [comment]
@salortiz 
```raku
 > my $nested = { dummy => <actual values> };
{dummy => (actual values)}
 > say $nested.AT-KEY('dummy')
(actual values)
 > $nested.=AT-KEY('dummy')
(actual values)
 > say $nested
(actual values)
```

The `.=` here  seems to work just fine!
